### ISSUE TITLE
Can't open application on Macbook Air M2

### ISSUE THREAD

**Issue by mparrett** [vincelwt/chatgpt-mac#1]
Hello,

Thanks for making this! I downloaded the arm64 image, copied ChatGPT to Applications, and tried to open it. I got the "damaged and can't be opened" prompt for unsigned apps. I attempted to follow the instructions below but didn't make any further progress. I also checked  my privacy settings, which should allow me to open it.

Do you know if there's a workaround?

Mac OS Version: 13.0

## Can't be opened
<img width="295" alt="image" src="https://user-images.githubusercontent.com/214866/205126507-ab84250a-e0e9-4477-991d-07afc672c288.png">

## Override security settings
<img width="576" alt="image" src="https://user-images.githubusercontent.com/214866/205126547-a40a3861-86d4-496c-ad72-e17645e31aff.png">

## Privacy settings
<img width="470" alt="image" src="https://user-images.githubusercontent.com/214866/205127377-3243ec2d-43f6-4a3b-bd4f-82595ad1f7b4.png">

Thanks,
Matt

**Comment by brennanerbz** [comment]
+1

**Comment by 8times4** [comment]
@mparrett @brennanerbz you can build it yourself via node/npm. (You need git & npm installed) 

```
https://github.com/vincelwt/chatgpt-mac.git
cd chatgpt-mac
npm install --legacy-peer-deps
npm run make
open out/ChatGPT-darwin-arm64
```
then just drag the app to your Applications folder. 

Hope this helps!
-8x4

**Comment by mparrett** [comment]
Perfect, thanks!Sent from my iPhoneOn Dec 1, 2022, at 13:19, 8x4 ***@***.***> wrote:﻿
@mparrett @brennanerbz you can build it yourself via node/npm. (You need git & npm installed)
https://github.com/vincelwt/chatgpt-mac.git
cd chatgpt-mac
npm install --legacy-peer-deps
npm run make
open out/ChatGPT-darwin-arm64

then just drag the app to your Applications folder.
Hope this helps!
-8x4

**Comment by mparrett** [comment]
Thanks for the quick response!

**Comment by vincelwt** [comment]
Hey guys! Sorry haha I pushed this just before going to sleep and didn’t test it properly - let me check what’s wrong

**Comment by vincelwt** [comment]
Seems like this is related to this issue: https://github.com/electron-userland/electron-builder/issues/5850 
Might have to pay the 99$ to apple for signing

**Comment by 8times4** [comment]
@vincelwt the version you uploaded was just a corrupted build, but yeah, if you want all warnings gone, a signature is required, however warnings can be clicked through, if the package isn’t corrupted/damaged.

**Comment by vincelwt** [comment]
@8times4 that's what I thought but no, seems to be related to signing. I retried the build with a lot of different configs and only universal builds ends up not being "damaged" on arm. Check the issue above, seems to be fixable `sudo xattr -r -d com.apple.quarantine` but not ideal. Just renewed my Apple developers membership, will try signing

**Comment by vincelwt** [comment]
Ok that should be good to go! Managed to setup code signing, can you try with the 0.0.2 release?  https://github.com/vincelwt/chatgpt-mac/releases/tag/v0.0.2

Thanks for reporting guys
