### ISSUE TITLE
Bug with multiple displays

### ISSUE THREAD

**Issue by aeromusek** [vincelwt/chatgpt-mac#10]
The pop-up window doesn't seem to be fully multi-screen aware yet.

**Expected behavior:** when using the cmd+shift+g keyboard shortcut, the pop-up window appears on the display with the currently-active menubar
**Current behavior:** pop-up window appears on the screen where the menubar icon was most recently _clicked_ (with the mouse), even if the active menubar has shifted to another display.

**Comment by StephenPerreira** [comment]
Same issue. When swiping between multiple virtual desktops it switches back to the one that was originally used.

**Comment by vincelwt** [comment]
Should be fixed with the the latest release! If you guys can confirm :)

**Comment by aeromusek** [comment]
@vincelwt I'm seeing the fix for virtual desktops, but _not_ yet for multiple physical displays (it still behaves as described in the original ticket).

Thanks for the quick updates!
