### ISSUE TITLE
[Feature] on the chat when pressing enter it should send message rather than add a new line

### ISSUE THREAD

**Issue by RusabKhan** [vincelwt/chatgpt-mac#110]
When I press enter when writing to ChatGPT it creates a new line. Can you make it so that pressing enter actually sends the message? Usually, that is the case in Chatting applications. For a new line, the user can press **shift+enter**.

<img width="452" alt="Screenshot 2023-04-09 at 9 33 26 PM" src="https://user-images.githubusercontent.com/74367699/230784961-3a889184-1835-49d6-9ff8-4ad1ab0872cd.png">

**Comment by weijay0804** [comment]
When you enlarge the window, pressing the **enter key** will send the message, while pressing **shift+enter** will create a new line.
<img width="924" alt="截圖 2023-04-10 下午7 43 40" src="https://user-images.githubusercontent.com/74105438/230895943-0b5f1b07-cda9-4505-ae80-48467b3797db.png">
