### ISSUE TITLE
Anyone made Text to speech support?

### ISSUE THREAD

**Issue by cantonalex** [vincelwt/chatgpt-mac#12]
So you can hear your responses rather reading them.

**Comment by vincelwt** [comment]
Thanks but I don't think that would be very relevant in the app at the moment, as most people can read the responses. Would also be a challenge for formatted data (code, titles, links, etc.).

**Comment by cantonalex** [comment]
probably an oversight on your part https://twitter.com/viticci/status/1600140302089687041
