### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by StephenPerreira** [vincelwt/chatgpt-mac#15]
I am getting an error "Too many requests, please slow down" when using this program but I am able to use the website directly (chat.openai.com) without issue. Not sure what changed in the latest release to cause this.

**Comment by phanhaiquang** [comment]
[MacOS, Intel] I had similar issue. After some success query, it shows "too many requests, please slow down" all the time.
But after I terminated the job and execute again, it resumes working.

**Comment by vincelwt** [comment]
Could you send a screenshot? Is it showing that as an error message inside the chat?

**Comment by jet3004** [comment]
It's nothing to do with this app – it's a OpenAI server side issue due to high demand. It happens just as easily in a browser (which, to be fair, this is essentially a browser wrapper, so of course it can happen here).

**Comment by vincelwt** [comment]
Yeah was I thinking! Thanks for confirming @jet3004
