### ISSUE TITLE
can't sign out once signed in 

### ISSUE THREAD

**Issue by parthsav** [vincelwt/chatgpt-mac#156]
there is no way to signout currently once you are logged in

**Comment by parthsav** [comment]
also after uninstalling and reinstalling the app on Mac, it still logs in as the old user. 
Note, also ran these but it made no difference 
rm -rf ~/Library/HTTPStorages/com.vincelwt.chatgptmac
rm ~/Library/Preferences/com.vincelwt.chatgptmac.plist
rm -rf ~/Library/Caches/com.vincelwt.chatgptmac
rm -rf ~/Library/Caches/com.vincelwt.chatgptmac.ShipIt

**Comment by ganjinhyouweisheng** [comment]
Have you solved it?

**Comment by glassysky1** [comment]
> 

you can resize the window

**Comment by glassysky1** [comment]
@parkersavi @ganjinhyouweisheng 
![Uploading Snipaste_2024-10-29_09-22-47.png…]()

**Comment by parthsav** [comment]
i resized the window and still it didnt help in my case. I need the desktop app to sign me out so I could log in with a different login. In my case it magically logged me out after few days. That's the only thing that worked for me 
I can see the logout option now. which is basically clicking on my name in the chat window
