### ISSUE TITLE
After logging in, I still see the login prompt

### ISSUE THREAD

**Issue by markerdmann** [vincelwt/chatgpt-mac#2]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/187540/205218353-aadac92b-1863-4eb7-b0e8-7d8497ebea3e.png">

When I click log in it takes to the browser to log in, but after completing that flow, nothing changes and I still see this prompt.

**Comment by vincelwt** [comment]
Hey! Thanks for reporting, can you try with the latest release?  https://github.com/vincelwt/chatgpt-mac/releases/tag/v0.0.3 
I think it was an issue with opening all links in the browser

**Comment by tiagomaricate** [comment]
> Hey! Thanks for reporting, can you try with the latest release? https://github.com/vincelwt/chatgpt-mac/releases/tag/v0.0.3
> I think it was an issue with opening all links in the browser

I'm using the 0.0.5 and have exact the same problem.
Using MacBook Pro M2.

**Comment by xbladesub** [comment]
Same - always logout by itslef
