### ISSUE TITLE
For all looking to run on Mac

### ISSUE THREAD

**Issue by worldoptimizer** [vincelwt/chatgpt-mac#20]
I found Menubar X, an app exclusive to Mac, to be a great solution for placing arbitrary apps in the menu bar. It's been working great for me with ChatGPT and Open AI Playground. I'm thankful to the contributors of the GitHub project for their hard work, but I'm also glad to have found an alternative that works better for my needs.

**Comment by vincelwt** [comment]
Thanks but here is for posting bugs and features requests related to this app.

**Comment by worldoptimizer** [comment]
There was no discussion section. Sorry.
