### ISSUE TITLE
Can't run on M1 macs

### ISSUE THREAD

**Issue by Explosion-Scratch** [vincelwt/chatgpt-mac#28]
I tried both the Intel and Arm 64 versions and they both said "Installation failed"

**Comment by vincelwt** [comment]
Runs fine with my M1, what's your mac version and when is the error showing?

**Comment by burdo3417** [comment]
works great macbook pro 14 m1 pro. macos 13.01

**Comment by Explosion-Scratch** [comment]
> Runs fine with my M1, what's your mac version and when is the error showing?

Just gives an alert saying "Installation failed"

**Comment by Explosion-Scratch** [comment]
Huh, tried again while screen recording, can't reproduce
