### ISSUE TITLE
Enable Paste

### ISSUE THREAD

**Issue by panckreous** [vincelwt/chatgpt-mac#3]
Hey Vince,
Thanks for making this. 

Trying to log in but it seems I cant paste into the window and right clicks aren't triggering anything, either. Any chance those can be enabled? 

Tested in macos Monterey 12.6.1 and the latest Ventura, same behavior in both.

thanks again

**Comment by alexandrosk** [comment]
Yes its not nice to type your password in a popup page that you don't see anything or paste

**Comment by vincelwt** [comment]
Hey! 
Can you try with the latest release? Should be fixed 😉 https://github.com/vincelwt/chatgpt-mac/releases/tag/v0.0.4

**Comment by panckreous** [comment]
perfect, thank you
