### ISSUE TITLE
code answers tend to get cut before end of answer. 

### ISSUE THREAD

**Issue by esaruoho** [vincelwt/chatgpt-mac#34]
I've been seeing this a bit, can I send screenshots privately to you @vincelwt ? I've seen three answers where the code is obviously cut mid-word and i don't know how to get it to show the whole result. Is there a limitation to the amount of code used / shown in the codeblock, and does that cause issues with the rest of the answer? i'm fine with some of the codeblock being interrupted (because too long), but then losing the rest of the answer (which might contain more than just the code) is a bit of a shame.

**Comment by vincelwt** [comment]
Pretty sure this is a problem with chatgpt not the Mac app! Responses have a certain size limit. You can usually ask it to give you the rest of the answer starting from x

**Comment by esaruoho** [comment]
@vincelwt thanks! i'll try and see if it can continue!
