### ISSUE TITLE
I press the sign up button for openai but it does not do anything. thx

### ISSUE THREAD

**Issue by kocoman2** [vincelwt/chatgpt-mac#38]
I press the sign up button for openai but it does not do anything. thx

**Comment by esaruoho** [comment]
@kocoman2 are you able to sign up using the openai site on your browser? maybe create an account first, and then just log in with this tool? that's what i did.

**Comment by lektriq** [comment]
I think OpenAI are having an issue with unexpectedly high demand. Login is also in a login loop on the browser and desktop here.

**Comment by lektriq** [comment]
Seems to be fixed here now, logged in without issues.
