### ISSUE TITLE
Icon on the dock mismatches with size with macOS Monterey / Ventura "world"

### ISSUE THREAD

**Issue by esaruoho** [vincelwt/chatgpt-mac#39]
<img width="278" alt="Näyttökuva 2022-12-7 kello 22 54 52" src="https://user-images.githubusercontent.com/4966687/206293842-f52921b0-e63f-4849-bd24-df0e4562ef19.png">

Expectation is that the icon fits the rest of these icon-sizes :)

**Comment by vincelwt** [comment]
Yes a PR was submitted for that already (#24) , will be part of next release. Not too pressing as it's not a dock app
