### ISSUE TITLE
macOS Ventura: the menu and app windows only open in a specific Space

### ISSUE THREAD

**Issue by TasseDeCafe** [vincelwt/chatgpt-mac#45]
After having used the app once, it stays linked with a specific Space. Instead, the same window/menu should be accessible from any Space, without switching to the Space where it was first opened.

**Comment by samasante** [comment]
This is fixed in #17 by setting `win.setAlwaysOnTop(flag[, level][, relativeLevel])` (https://www.electronjs.org/docs/latest/api/browser-window)

**Comment by TasseDeCafe** [comment]
Indeed, I just updated. Thanks!
