### ISSUE TITLE
What are you doing with analytics data?

### ISSUE THREAD

**Issue by joelmellon** [vincelwt/chatgpt-mac#94]
I see you're using analytics software: https://github.com/vincelwt/chatgpt-mac/blob/main/index.js#L22

What data are you collecting, and why?

**Comment by joelmellon** [comment]
> sue

lol, this question is largely to start a discussion publicly. I won't use this package until I know what's going on, and probably not even then.

**Comment by rip-off-hb** [comment]
Quickly skimming through the code (as of 2023-03-05) and the Nukleus analytics JS API that I was not familiar with, users are not tracked. Only app opens are anonymously tracked by the init call - which is fair in my book.

https://docs.nucleus.sh/modules/javascript-module

**Comment by vincelwt** [comment]
Hey, 
There was already an issue opened about this: https://github.com/vincelwt/chatgpt-mac/issues/16 
No user specific data tracked indeed, only general stats. 

-- 

> I recommend you sue/report the author directly in case he might not reply. 

🤣🤣🤣 Okay
