### ISSUE TITLE
macos打开白屏

### ISSUE THREAD

**Issue by JackShijt** [vincelwt/chatgpt-mac#97]
![image](https://user-images.githubusercontent.com/56808243/223003791-ab267df0-8e6b-4809-9632-8b91aa40b6ea.png)

**Comment by KaelInvoker** [comment]
我的也白屏了 有知道怎么解决么

**Comment by JackShijt** [comment]
> 我的也白屏了 有知道怎么解决么

没解决呢

**Comment by JackShijt** [comment]
苹果系统把chatgpt给禁了，可以用别的系统或者微信内打开

**Comment by vincelwt** [comment]
English please
